# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-11 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gprotein', models.CharField(max_length=32)),
                ('log10_evalue_rab', models.FloatField()),
                ('log10_evalue_nonrab', models.FloatField(blank=True, null=True)),
                ('rabf', models.CharField(max_length=256)),
                ('israb', models.BooleanField()),
                ('rab_subfamily', models.CharField(max_length=16)),
                ('rab_subfamily_score', models.FloatField()),
                ('rab_subfamily_top5', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='NcbiTaxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('taxon_id', models.IntegerField(unique=True)),
                ('node_rank', models.CharField(max_length=64)),
                ('taxon_name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protein', models.CharField(max_length=32, unique=True)),
                ('transcript', models.CharField(max_length=32, unique=True)),
                ('gene', models.CharField(max_length=64)),
                ('uniprot', models.CharField(blank=True, max_length=32)),
                ('description', models.TextField()),
                ('seq', models.TextField()),
                ('comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taxon', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('name_common', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='annotation',
            name='protein',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Protein'),
        ),
        migrations.AddField(
            model_name='annotation',
            name='taxonomy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='browser.Taxonomy'),
        ),
    ]
