# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protein',
            name='protein',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='protein',
            name='transcript',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
